server:
  port: 8081
spring:
  application:
    name: shark
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.137.123.85:3306/happy_go?useSSL=false&serverTimezone=UTC
    username: root
    password: 472020
  redis:
    host: 8.137.123.85
    port: 6379
    password: 472020
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.shark.entity # 别名扫描包
logging:
  level:
    com.shark: debug
  pattern:
    dateformat: mm:ss.SSS